[[redirects]]
  from = "/api/faa/*"
  to = "https://nasstatus.faa.gov/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/txdot/*"
  to = "https://its.txdot.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/wpc/*"
  to = "https://www.wpc.ncep.noaa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/spc/*"
  to = "https://www.spc.noaa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/swpc/*"
  to = "https://services.swpc.noaa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/nhc/*"
  to = "https://www.nhc.noaa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/sdo/*"
  to = "https://sdo.gsfc.nasa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/awc/*"
  to = "https://aviationweather.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/nesdis/*"
  to = "https://cdn.star.nesdis.noaa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/cpc/*"
  to = "https://www.cpc.ncep.noaa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/nws-api/*"
  to = "https://api.weather.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/nws/*"
  to = "https://forecast.weather.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/opc/*"
  to = "https://ocean.weather.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/nasa/*"
  to = "https://api.nasa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/noaa-tsunami/*"
  to = "https://www.tsunami.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/nwsimg/*"
  to = "https://www.weather.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/aviationwx/*"
  to = "https://www.aviationweather.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/graphwx/*"
  to = "https://graphical.weather.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/iem/*"
  to = "https://mesonet.agron.iastate.edu/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/rainviewer/*"
  to = "https://api.rainviewer.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/sunrise-sunset/*"
  to = "https://api.sunrise-sunset.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/faa-cams/*"
  to = "https://weathercams.faa.gov/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/rucsoundings/*"
  to = "https://rucsoundings.noaa.gov/:splat"
  status = 200
  force = true
